### ISSUE TITLE
Some game names are either not or misdetected

### ISSUE THREAD

**Issue by Masamune3210** [giwty/switch-library-manager#50]
I have 3 game examples where the game name is either not detected, which leaves a folder name with just the titleid like "[0100E000089F2000]" for "Portal Knights (En,Fr,De,Es,It,Por,Ru,Kor) [0100E000089F2000] [v0]", or misdetected, , in which case it just leaves whatever it could detect, like "4 [010009400DD38000]" for "Rune Factory 4 Special (Kor) [010009400DD38000] [v0] (1G+1D)"

**Comment by giwty** [comment]
This happens because the titles original name is in Korean, and while trying to convert the name to unicode safe, it ends up the way you see it.
I'll add a fix that whenever Tinfoil provides me with a non English title, to grab the English title from the file itself (assuming you have prod.keys)

**Comment by giwty** [comment]
should be fixed in 1.3.7

**Comment by jangshik** [comment]
issue is still there in 1.4.0, it is named as blank but korean letters could be seen in gui. 
from windows gui and linux cli
